[build]
  command = "yarn build"
  publish = "build"

[context.production]
  environment = { NODE_VERSION = "16.14.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.14.2" }

[context.branch-deploy]
  environment = { NODE_VERSION = "16.14.2" }
